### ISSUE TITLE
Typo in updatedaemons.sh 

### ISSUE THREAD

**Issue by krath1bb** [PowerTuneDigital/PowerTuneDigitalOfficial#76]
https://github.com/PowerTuneDigital/PowerTuneDigitalOfficial/blob/c2166c338b9febad52295ea5866afe38b7f2e6ff/updatedaemons.sh#L6

The directory referenced in line 6 has an extra space in it. This is in both the /home/pi and /home/pi/src files.

**Comment by PowerTuneDigital** [comment]
Fixed
