### ISSUE TITLE
Referencing wrong directory in updateUserDashboards.sh 

### ISSUE THREAD

**Issue by krath1bb** [PowerTuneDigital/PowerTuneDigitalOfficial#77]
https://github.com/PowerTuneDigital/PowerTuneDigitalOfficial/blob/ec2aa4cba001a8665912f4e2797b085f3c9a223b/updateUserDashboards.sh#L3-L7

It looks like the directory being referenced in both the home and src folders is incorrect. Its referencing srcofficial when it should be src.

**Comment by PowerTuneDigital** [comment]
fixed
