### ISSUE TITLE
Buildroot no longer complies in any version of linux

### ISSUE THREAD

**Issue by K4HVH** [PowerTuneDigital/PowerTuneDigitalOfficial#88]
I am unsure if I am missing something or not, so sorry if that is the case.

However, I have tried Ubuntu 20.10, 17.04, and 18.04 in an attempt to get the buildroot to compile. But nothing seems to work.
I have patched a couple reoccuring issues however I still cannot get it to compile.

Is there a newer version (Which supports RPI4 (Like you guys have on your site ([Here](https://www.powertunedigital.com/products/v4-to-v5-upgrade?pr_prod_strat=use_description&pr_rec_id=1d7f0e6fe&pr_rec_pid=7186470174768&pr_ref_pid=6805440593968&pr_seq=uniform))) that we can use to compile the buildroot?

-Kenny

**Comment by PowerTuneDigital** [comment]
Pi3 Version is not used anymore as the Hardware is not available anymore , new image for PI4 is based on Yocto
